DROP VIEW vw_all;

CREATE VIEW  vw_all AS ( SELECT extdat.ext_id,
    ((((((('file '''::text || fetchpreftext('archive_path'::text)) || '/'::text) || "left"(extdat.ext_filename, 8)) || '/'::text) || trs_tg.tg_decimal) || '/'::text) || extdat.ext_filename) || ''''::text AS ffurl,
    (((((fetchpreftext('archive_path'::text) || '/'::text) || "left"(extdat.ext_filename, 8)) || '/'::text) || trs_tg.tg_decimal) || '/'::text) || extdat.ext_filename AS fpath,
    extdat.ext_filename AS filename,
    extdat.ext_radio AS radio,
    extdat.ext_time AS filets,
    extdat.ext_sys AS county,
    extdat.ext_sys1 AS sys1,
    extdat.ext_sys2 AS sys2,
    extdat.ext_job AS jobnum,
    trs_tg.tg_decimal AS talkgroup,
    trs_tg.tg_hex AS hex,
    trs_tg.tg_alpha_tg AS atag,
    trs_tg.tg_mode AS mode,
    trs_tg.tg_desc AS descrip,
    trs_tg.tg_tag AS tag,
    trs_tg.tg_category AS category,
    "left"(extdat.ext_filename, 15)::timestamp with time zone AS ts_tz,
    "left"(extdat.ext_filename, 8)::date AS dt,
    to_char("left"(extdat.ext_filename, 15)::timestamp without time zone, 'HH24:MI:SS'::text)::time without time zone AS hms,
    to_char("left"(extdat.ext_filename, 15)::timestamp without time zone, 'HH24'::text)::integer AS hod,
    to_char("left"(extdat.ext_filename, 15)::timestamp without time zone, 'MI'::text)::integer AS moh,
    to_char("left"(extdat.ext_filename, 15)::timestamp without time zone, 'SS'::text)::integer AS soh,
    to_char("left"(extdat.ext_filename, 15)::timestamp without time zone, 'SSSS'::text)::integer AS sod,
    to_char("left"(extdat.ext_filename, 15)::timestamp without time zone, 'SSSS'::text)::integer / 60 AS mod,
    to_char("left"(extdat.ext_filename, 15)::date::timestamp with time zone, 'day'::text) AS day,
    to_char("left"(extdat.ext_filename, 15)::date::timestamp with time zone, 'month'::text) AS mon,
    EXTRACT(Day FROM "left"(extdat.ext_filename, 15)::timestamp without time zone)::integer AS dom,
    date_part('YEAR'::text, to_char("left"(extdat.ext_filename, 15)::timestamp without time zone, 'YYYY-MM-DD HH24:MI:SS'::text)::timestamp with time zone) AS yr,
    date_part('month'::text, to_char("left"(extdat.ext_filename, 15)::timestamp without time zone, 'YYYY-MM-DD HH24:MI:SS'::text)::timestamp with time zone) AS mo,
    date_part('Dow'::text, to_char("left"(extdat.ext_filename, 15)::timestamp without time zone, 'YYYY-MM-DD HH24:MI:SS'::text)::timestamp with time zone) AS dow,
    date_part('DOY'::text, to_char("left"(extdat.ext_filename, 15)::timestamp without time zone, 'YYYY-MM-DD HH24:MI:SS'::text)::timestamp with time zone) AS doy,
    date_part('WEEK'::text, to_char("left"(extdat.ext_filename, 15)::timestamp without time zone, 'YYYY-MM-DD HH24:MI:SS'::text)::timestamp with time zone) AS wno
   FROM extdat
     JOIN trs_tg ON extdat.ext_talkgroup = trs_tg.tg_decimal);

